feat: email scrubbing
greatmindsorg/aws-log-ingestion pull request #1
Opened 2022-01-13 22:42 UTC by DavidSAtGM

Initial PR for eval/discussion, needs unit testing still

2022-01-14 15:35 UTC, TRiggAtGM requested changes
Your docstring for _remove_pii_email_addresses is far too long. Format for those should be

```python
def function_name(parameter: type) -> return_type:
    """
    Summarize the function in a single declarative sentence.

    In depth description of the whole shebang.
    """
    return return_value
```

2022-01-19 18:34 UTC, TRiggAtGM commented
Sorry. One more req. Can you change "Matches and replaces" to "Match and replace"? That's the preferred sentence structure for docstrings. But like... also. This is piddly enough I'm gonna approve

2022-01-19 18:35 UTC, TRiggAtGM approved these changes

2022-03-08 20:04 UTC, codeglider24 approved these changes
LGTM

2022-03-08 20:04 UTC, merged